# This access_token is a User access token w/ permission to access API
access_token: <FILL IN>

page_total: 5   # Should be a maximum of 1,000
search_total: 25   # You can query a maximum of 5,000 ads

# You can provide search terms and/or page IDs.
search_terms: clinton
page_ids:
  # -

# Fields for querying all possible metadata from the API
query_fields:
  - ad_creation_time
  - ad_creative_body
  - ad_creative_link_caption
  - ad_creative_link_description
  - ad_creative_link_title
  - ad_delivery_start_time
  - ad_delivery_stop_time
  - ad_snapshot_url
  - demographic_distribution
  - funding_entity
  - impressions
  - page_id
  - page_name
  - region_distribution
  - spend

# Fields which are included in the main CSV, including derived fields
output_fields:
  - ad_id
  - page_id
  - page_name
  - ad_creative_body
  - ad_creative_link_caption
  - ad_creative_link_description
  - ad_creative_link_title
  - ad_delivery_start_time
  - ad_delivery_stop_time
  - funding_entity
  - impressions_min
  - impressions_max
  - spend_min
  - spend_max
  - ad_url

# Fields for the unnested CSVs
demo_fields:
  - ad_id
  - age
  - gender
  - percentage

region_fields:
  - ad_id
  - region
  - percentage
